import {ServerlessForm} from './lib/serverless_form.js';
import {SpreadsheetHelper} from './lib/spreadsheet_helper.js';
import {GoogleSpreadsheet} from 'google-spreadsheet';
import {JWT} from 'google-auth-library';

async function handler(
  event,
  {
    googleServiceAccountEmail,
    googlePrivateKey,
    spreadsheetId,
    spreadsheetSheetTitle,
    apexDomain,
  },
) {
  if (
    googleServiceAccountEmail &&
    googlePrivateKey &&
    spreadsheetId &&
    spreadsheetSheetTitle &&
    apexDomain
  ) {
    const serverlessForm = new ServerlessForm(event, apexDomain);
    const googleAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: googleServiceAccountEmail,
      key: googlePrivateKey.replace(/\\n/g, '\n'),
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const googleService = new GoogleSpreadsheet(spreadsheetId, googleAuth);
    const spreadsheetHelper = new SpreadsheetHelper(
      googleService,
      spreadsheetSheetTitle,
    );

    if (!serverlessForm.isValidRequest) {
      return ServerlessForm.invalidMethodResponse;
    } else if (!serverlessForm.isValidDomain) {
      return ServerlessForm.teapotResponse;
    } else {
      await spreadsheetHelper.handle(serverlessForm.sheetRow);
      return serverlessForm.redirectResponse;
    }
  }
  return ServerlessForm.teapotResponse;
}
export {handler};
